
name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write-all

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
    - id: deploy
      name: Deploy
      uses: madawotee/github-actions-deploy-docker-to-ec2@v0.5.8
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_default_region: eu-west-1
        # dot_env: ${{ secrets.DOT_ENV }}
        app_port: 3000
