name: Deploy-PR
on:
  pull_request:
    branches: [ main ]
    #teststtst 4444
permissions:
  contents: write
jobs:
  EC2-Deploy:
    # if the branch name of the PR does not contain 'skip-deploy'
    if: "!contains(github.head_ref, 'skip-deploy')"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
      - id: deploy
        name: Deploy
        uses: madawotee/github-actions-deploy-docker-to-ec2@v0.5.8
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: eu-west-1
          app_port: 3000

  # - name: Clear Cache
  # run: |
  #   echo "::set-output name=cache-hit::false"
  # if: steps.cache.outputs.cache-hit == 'true'          